In [1]:
pip install numpy


In [2]:
import numpy as np


In [3]:
#Q2
followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Followers Array:")
print(followers)

print("\nShape:", followers.shape)
print("Dimensions:", followers.ndim)
print("Data Type:", followers.dtype)

Followers Array:
[   1200   15000   67000  340000 1250000]

Shape: (5,)
Dimensions: 1
Data Type: int64


In [4]:
#Q3
order_ids = np.arange(101, 111)

print("Order IDs:")
print(order_ids)

print("\nSize:", order_ids.size)

Order IDs:
[101 102 103 104 105 106 107 108 109 110]

Size: 10


In [5]:
#Q4
like_matrix = np.eye(3)

print("Identity Matrix:")
print(like_matrix)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#Q5
scores = [45, 67, 120, 89, 54]

score_array = np.array(scores)

print("Cricket Scores:")
print(score_array)

print("\nMemory used by each score:", score_array.itemsize, "bytes")

Cricket Scores:
[ 45  67 120  89  54]

Memory used by each score: 8 bytes
