#Q1Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.


In [ ]:

import numpy as np

ratings = np.array([
    [4, 5, 3, 4, 5],
    [3, 4, 5, 2, 4],
    [5, 5, 4, 3, 4],
    [2, 3, 4, 5, 3]
])
second_third_users = ratings[1:3, :]
print(second_third_users)

[[3 4 5 2 4]
 [5 5 4 3 4]]


Q2 Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>


In [ ]:

steps = np.array([7500, 8200, 9000, 6800, 8500, 7200, 9100, 8800, 6500, 9300])

high_step_days = steps[steps > 8000]
print(high_step_days)

[8200 9000 8500 9100 8800 9300]


Q3.Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.


In [ ]:

scores = np.array([180, 165, 200, 145, 190, 210, 155, 175])

selected_scores = scores[[1, 4, 6]]
print(selected_scores)

[165 190 155]


Q4.Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>


In [ ]:

prices = np.array([999, 1499, 2999, 4999, 7999])

discounted_prices = prices * 0.90
print(discounted_prices)

[ 899.1 1349.1 2699.1 4499.1 7199.1]


Q5.Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.


In [ ]:

ratings = np.array([4, -2, 0, 5, -3, 3, -1, 2])

ratings[ratings < 0] = 0
print(ratings)

[4 0 0 5 0 3 0 2]
