Q1.Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.



In [11]:
import numpy as np
friend1 = np.array([1500, 2500, 3500, 4500, 5500, 6500, 7500, 8500, 9500])
friend2 = np.array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

print(" Element-wise Addition:")
print(friend1 + friend2)

print("\nElement-wise Subtraction:")
print(friend1 - friend2)

print("\nElement-wise Multiplication:")
print(friend1 * friend2)

print("\n Element-wise Division:")
print(friend1 / friend2)

 Element-wise Addition:
[ 2500  4500  6500  8500 10500 12500 14500 16500 18500]

Element-wise Subtraction:
[500 500 500 500 500 500 500 500 500]

Element-wise Multiplication:
[ 1500000  5000000 10500000 18000000 27500000 39000000 52500000 68000000
 85500000]

 Element-wise Division:
[1.5        1.25       1.16666667 1.125      1.1        1.08333333
 1.07142857 1.0625     1.05555556]


Q2. Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.



In [12]:
user_preferences = np.array([
    [5, 4, 3],
    [2, 5, 3],
    [4, 2, 5]
])
song_popularity = np.array([
    [4, 2, 3],
    [3, 5, 2],
    [2, 4, 5]
])
recommendation_dot = np.dot(user_preferences, song_popularity)
recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("\n Recommendation Matrix using dot():")
print(recommendation_dot)

print("\n- Recommendation Matrix using matmul():")
print(recommendation_matmul)

print("\nDifference:")
print("For two 2D matrices, np.dot() and np.matmul() produce the same matrix multiplication result.")


 Recommendation Matrix using dot():
[[38 42 38]
 [29 41 31]
 [32 38 41]]

- Recommendation Matrix using matmul():
[[38 42 38]
 [29 41 31]
 [32 38 41]]

Difference:
For two 2D matrices, np.dot() and np.matmul() produce the same matrix multiplication result.


Q3. Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.


In [13]:
pixels = np.array([
    [120, 150, 180, 200],
    [100, 130, 160, 190],
    [90, 140, 170, 210],
    [110, 125, 155, 195]
])

transposed_pixels = pixels.T

print("\nOriginal Pixel Matrix:")
print(pixels)

print("\nTransposed Pixel Matrix:")
print(transposed_pixels)

print("\nMean:", np.mean(pixels))
print("Median:", np.median(pixels))
print("Standard Deviation:", np.std(pixels))
print("Variance:", np.var(pixels))


Original Pixel Matrix:
[[120 150 180 200]
 [100 130 160 190]
 [ 90 140 170 210]
 [110 125 155 195]]

Transposed Pixel Matrix:
[[120 100  90 110]
 [150 130 140 125]
 [180 160 170 155]
 [200 190 210 195]]

Mean: 151.5625
Median: 152.5
Standard Deviation: 36.08664702836771
Variance: 1302.24609375


Q4. Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>



In [14]:
correlation_grid = np.array([
    [4, 1, 2],
    [1, 5, 1],
    [2, 1, 6]
], dtype=float)

inverse_matrix = np.linalg.inv(correlation_grid)
determinant = np.linalg.det(correlation_grid)
eigenvalues, eigenvectors = np.linalg.eig(correlation_grid)

print("\nOriginal Matrix:")
print(correlation_grid)

print("\nInverse:")
print(inverse_matrix)

print("\nDeterminant:")
print(determinant)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Original Matrix:
[[4. 1. 2.]
 [1. 5. 1.]
 [2. 1. 6.]]

Inverse:
[[ 0.30851064 -0.04255319 -0.09574468]
 [-0.04255319  0.21276596 -0.0212766 ]
 [-0.09574468 -0.0212766   0.20212766]]

Determinant:
94.0

Eigenvalues:
[7.89510652 2.70759841 4.39729507]

Eigenvectors:
[[ 0.49725362  0.86427949  0.07589338]
 [ 0.43170413 -0.17059871 -0.88573564]
 [ 0.75257583 -0.47319874  0.45794385]]


Q5. Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.



In [15]:
orders = np.array([
    [120, 150, 180, 200, 220, 250],
    [100, 130, 160, 190, 210, 240]
])

print("\nOriginal Array:")
print(orders)

reshaped_orders = orders.reshape(3, 4)

print("\nReshaped to (3, 4):")
print(reshaped_orders)

flattened_orders = orders.flatten()

print("\nFlattened Array:")
print(flattened_orders)

part1, part2 = np.split(flattened_orders, 2)

print("\nFirst Half:")
print(part1)

print("\nSecond Half:")
print(part2)

stacked_orders = np.vstack((part1, part2))

print("\nVertically Stacked:")
print(stacked_orders)


Original Array:
[[120 150 180 200 220 250]
 [100 130 160 190 210 240]]

Reshaped to (3, 4):
[[120 150 180 200]
 [220 250 100 130]
 [160 190 210 240]]

Flattened Array:
[120 150 180 200 220 250 100 130 160 190 210 240]

First Half:
[120 150 180 200 220 250]

Second Half:
[100 130 160 190 210 240]

Vertically Stacked:
[[120 150 180 200 220 250]
 [100 130 160 190 210 240]]
